runtime: nodejs16
handlers:
  # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: dist/\1
    upload: dist/(.*\..+)$
  # Catch all other path to index.html (typical for single-page applications (SPAs) that handle routing on the client side.)
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65 # Adjust as necessary
  min_instances: 1 # Optional: Set a minimum number of instances
  max_instances: 2 # Set a maximum number of instances
